apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://api:6443
    insecure-skip-tls-verify: true
  name: default
users:
- name: superuser
  user:
    token: 086adda9-1a99-428c-985b-89429d5307ce # see .config/static-tokens.txt
contexts:
- context:
    cluster: default
    user: superuser
  name: superuser
current-context: superuser
